.PHONY: help up down web logs restart ps db-shell docker-up \
        worker-run worker-start worker-reload worker-stop worker-status worker-logs \
        web-start web-restart web-stop web-status web-logs reload

WORKER := $(HOME)/.darkflow/darkflow-run.sh
UID_ := $(shell id -u)
WEB_SVC := gui/$(UID_)/com.darkflow.web
WORKER_SVC := gui/$(UID_)/com.darkflow.worker

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*##' $(MAKEFILE_LIST) | awk 'BEGIN {FS=":.*##"}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

up: ## Start Postgres in the background (webapp runs on the host — see `make web`)
	docker compose up -d

web: ## Build and run the webapp as a host process (http://localhost:5555)
	cd webapp && pnpm build && PORT=5555 pnpm start

docker-up: ## Start Postgres + webapp in Docker (no cmux launch button; http://localhost:5555)
	docker compose --profile docker up -d

down: ## Stop all services
	docker compose down

logs: ## Stream Docker logs (Ctrl-C to stop)
	docker compose logs -f

restart: ## Restart Docker services
	docker compose restart

ps: ## Show running containers and their status
	docker compose ps

db-shell: ## Open a psql shell inside the Postgres container
	docker compose exec db psql -U darkflow darkflow

worker-run: ## Run the global Dark Flow worker in the foreground (live logs; Ctrl-C to stop)
	@if [ ! -f "$(WORKER)" ]; then echo "Worker not installed at $(WORKER) — run install.sh --self-update first."; exit 1; fi
	@if pgrep -f "$(WORKER)" >/dev/null 2>&1; then \
		echo "Worker already running in the background (PID $$(pgrep -f "$(WORKER)" | head -1)). Stop it first: make worker-stop"; exit 1; \
	fi
	bash "$(WORKER)"

worker-start: ## Start the global Dark Flow worker under launchd (auto-restart, survives reboot/logout)
	@if [ ! -f "$(WORKER)" ]; then echo "Worker not installed at $(WORKER) — run install.sh in a project first."; exit 1; fi
	launchctl bootstrap gui/$(UID_) $(HOME)/Library/LaunchAgents/com.darkflow.worker.plist
	@echo "Worker running under launchd. Logs: ~/.darkflow/worker.log (+ worker.out.log/worker.err.log)"

worker-reload: ## Restart the launchd-supervised worker in place
	launchctl kickstart -k $(WORKER_SVC)

worker-stop: ## Stop the launchd-supervised worker
	-launchctl bootout $(WORKER_SVC)

worker-status: ## Show launchd status of the worker + last log lines
	-launchctl print $(WORKER_SVC) 2>&1 | grep -E "state|pid" || echo "Not loaded"
	@tail -n 5 "$(HOME)/.darkflow/worker.log" 2>/dev/null || true

worker-logs: ## Tail the global worker log (Ctrl-C to stop)
	@tail -f "$(HOME)/.darkflow/worker.log"

web-start: ## Start the webapp under launchd (auto-restart, survives reboot/logout; needs a prior `make web` build)
	launchctl bootstrap gui/$(UID_) $(HOME)/Library/LaunchAgents/com.darkflow.web.plist
	@echo "Webapp running under launchd on :5555. Logs: ~/.darkflow/web.out.log / web.err.log"

web-restart: ## Rebuild the webapp, then restart the launchd-supervised process
	@cd webapp && pnpm build
	@launchctl kickstart -k $(WEB_SVC)

web-stop: ## Stop the launchd-supervised webapp
	-launchctl bootout $(WEB_SVC)

web-status: ## Show launchd status of the webapp
	-launchctl print $(WEB_SVC) 2>&1 | grep -E "state|pid" || echo "Not loaded"

web-logs: ## Tail the webapp launchd log (Ctrl-C to stop)
	@tail -f "$(HOME)/.darkflow/web.out.log" "$(HOME)/.darkflow/web.err.log"

reload: ## Load (first run) or restart (afterwards) both webapp + worker under launchd — one-shot
	@cd webapp && pnpm build
	@launchctl kickstart -k $(WEB_SVC) 2>/dev/null || launchctl bootstrap gui/$(UID_) $(HOME)/Library/LaunchAgents/com.darkflow.web.plist
	@launchctl kickstart -k $(WORKER_SVC) 2>/dev/null || launchctl bootstrap gui/$(UID_) $(HOME)/Library/LaunchAgents/com.darkflow.worker.plist
	@echo "web (:5555) + worker running under launchd. Logs: make web-logs / make worker-logs"

# darkflow:start
# Dark Flow — managed block. Regenerated by install.sh/update.sh. Do not edit between the markers.
.PHONY: df-help df-list df-sync df-force-install

df-help:  ## Dark Flow: list available df-* targets
	@grep -E '^df-[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort \
	  | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-26s\033[0m %s\n",$$1,$$2}'

df-list:  ## show this project's routine status (the global worker runs them automatically)
	~/.darkflow/darkflow-run.sh --list

df-sync:  ## push this project's GitHub issues + metadata to the web UI
	~/.darkflow/darkflow-run.sh --sync

df-force-install:  ## force-reinstall Dark Flow from remote (overwrites templates)
	bash <(curl -fsSL https://raw.githubusercontent.com/alifanov/darkflow/main/install.sh) --force --yes
# darkflow:end
