.PHONY: help up down web logs restart ps db-shell docker-up \
        worker-run worker-start worker-reload worker-stop worker-status worker-logs

WORKER := $(HOME)/.darkflow/darkflow-run.sh

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*##' $(MAKEFILE_LIST) | awk 'BEGIN {FS=":.*##"}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

up: ## Start Postgres in the background (webapp runs on the host — see `make web`)
	docker compose up -d

web: ## Build and run the webapp as a host process (http://localhost:5555)
	cd webapp && pnpm build && PORT=5555 pnpm start

docker-up: ## Start Postgres + webapp in Docker (no cmux launch button; http://localhost:5555)
	docker compose --profile docker up -d

down: ## Stop all services
	docker compose down

logs: ## Stream Docker logs (Ctrl-C to stop)
	docker compose logs -f

restart: ## Restart Docker services
	docker compose restart

ps: ## Show running containers and their status
	docker compose ps

db-shell: ## Open a psql shell inside the Postgres container
	docker compose exec db psql -U darkflow darkflow

worker-run: ## Run the global Dark Flow worker in the foreground (live logs; Ctrl-C to stop)
	@if [ ! -f "$(WORKER)" ]; then echo "Worker not installed at $(WORKER) — run install.sh --self-update first."; exit 1; fi
	@if pgrep -f "$(WORKER)" >/dev/null 2>&1; then \
		echo "Worker already running in the background (PID $$(pgrep -f "$(WORKER)" | head -1)). Stop it first: make worker-stop"; exit 1; \
	fi
	bash "$(WORKER)"

worker-start: ## Start the global Dark Flow worker in the background (serves every project)
	@if [ ! -f "$(WORKER)" ]; then echo "Worker not installed at $(WORKER) — run install.sh in a project first."; exit 1; fi
	@if pgrep -f "$(WORKER)" >/dev/null 2>&1; then \
		echo "Worker already running (PID $$(pgrep -f "$(WORKER)" | head -1))."; \
	else \
		nohup bash "$(WORKER)" >/dev/null 2>>"$(HOME)/.darkflow/worker.err.log" & \
		sleep 1; echo "Worker started (PID $$(pgrep -f "$(WORKER)" | head -1)). Logs: ~/.darkflow/worker.log"; \
	fi

worker-reload: ## Stop the running worker, then run a fresh one in the foreground (live logs; Ctrl-C to stop)
	@if [ ! -f "$(WORKER)" ]; then echo "Worker not installed at $(WORKER) — run install.sh --self-update first."; exit 1; fi
	@pkill -f "$(WORKER)" 2>/dev/null && echo "Stopped old worker." || echo "No worker was running."
	@sleep 1
	bash "$(WORKER)"

worker-stop: ## Stop the global Dark Flow worker
	@pkill -f "$(WORKER)" 2>/dev/null && echo "Worker stopped." || echo "Worker was not running."

worker-status: ## Show whether the global worker is running + last log lines
	@if pgrep -f "$(WORKER)" >/dev/null 2>&1; then \
		echo "Running (PID $$(pgrep -f "$(WORKER)" | head -1))"; \
	else echo "Not running"; fi
	@tail -n 5 "$(HOME)/.darkflow/worker.log" 2>/dev/null || true

worker-logs: ## Tail the global worker log (Ctrl-C to stop)
	@tail -f "$(HOME)/.darkflow/worker.log"

# darkflow:start
# Dark Flow — managed block. Regenerated by install.sh/update.sh. Do not edit between the markers.
.PHONY: df-help df-list df-sync df-force-install

df-help:  ## Dark Flow: list available df-* targets
	@grep -E '^df-[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort \
	  | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-26s\033[0m %s\n",$$1,$$2}'

df-list:  ## show this project's routine status (the global worker runs them automatically)
	~/.darkflow/darkflow-run.sh --list

df-sync:  ## push this project's GitHub issues + metadata to the web UI
	~/.darkflow/darkflow-run.sh --sync

df-force-install:  ## force-reinstall Dark Flow from remote (overwrites templates)
	bash <(curl -fsSL https://raw.githubusercontent.com/alifanov/darkflow/main/install.sh) --force --yes
# darkflow:end
